// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flares/v1beta/contract.proto

package types

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgContract struct {
	Id             string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator        github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	Module         string                                        `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Key            string                                        `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Receiver       string                                        `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Accept         string                                        `protobuf:"bytes,6,opt,name=accept,proto3" json:"accept,omitempty"`
	DurationHeight int32                                         `protobuf:"varint,7,opt,name=durationHeight,proto3" json:"durationHeight,omitempty"`
	Bottom         string                                        `protobuf:"bytes,8,opt,name=bottom,proto3" json:"bottom,omitempty"`
	Height         uint64                                        `protobuf:"fixed64,9,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *MsgContract) IsAuctions() bool { return m.DurationHeight >= 0 }

func (m *MsgContract) Reset()         { *m = MsgContract{} }
func (m *MsgContract) String() string { return proto.CompactTextString(m) }
func (*MsgContract) ProtoMessage()    {}
func (*MsgContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdae3fe79527cbf4, []int{0}
}
func (m *MsgContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgContract.Merge(m, src)
}
func (m *MsgContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgContract proto.InternalMessageInfo

func (m *MsgContract) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgContract) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *MsgContract) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *MsgContract) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MsgContract) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgContract) GetAccept() string {
	if m != nil {
		return m.Accept
	}
	return ""
}

func (m *MsgContract) GetDurationHeight() int32 {
	if m != nil {
		return m.DurationHeight
	}
	return 0
}

func (m *MsgContract) GetBottom() string {
	if m != nil {
		return m.Bottom
	}
	return ""
}

func (m *MsgContract) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgContract)(nil), "flares.flares.v1beta1.MsgContract")
}

func init() { proto.RegisterFile("flares/v1beta/contract.proto", fileDescriptor_bdae3fe79527cbf4) }

var fileDescriptor_bdae3fe79527cbf4 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xc1, 0x4a, 0xf3, 0x40,
	0x18, 0xec, 0xa6, 0x7f, 0xd3, 0x76, 0xff, 0x9f, 0xf2, 0xb3, 0xa8, 0x2c, 0x45, 0x62, 0xf0, 0x20,
	0x39, 0xd8, 0x84, 0xe2, 0x13, 0xb4, 0x82, 0x08, 0xe2, 0x25, 0x47, 0x6f, 0x9b, 0xdd, 0xed, 0x76,
	0x69, 0x93, 0x0d, 0xbb, 0xdb, 0x6a, 0xdf, 0xc2, 0x47, 0xf0, 0x71, 0x3c, 0xf6, 0xe8, 0x49, 0xa4,
	0x7d, 0x0b, 0x4f, 0x92, 0x6c, 0x2a, 0xe2, 0xe9, 0x9b, 0x99, 0xcc, 0x4c, 0x60, 0x16, 0x9e, 0xce,
	0x96, 0x44, 0x73, 0x93, 0xac, 0xc7, 0x19, 0xb7, 0x24, 0xa1, 0xaa, 0xb0, 0x9a, 0x50, 0x1b, 0x97,
	0x5a, 0x59, 0x85, 0x8e, 0xdd, 0xd7, 0xb8, 0x39, 0xce, 0x34, 0x1e, 0x1e, 0x09, 0x25, 0x54, 0xed,
	0x48, 0x2a, 0xe4, 0xcc, 0xe7, 0x2f, 0x1e, 0xfc, 0x7b, 0x6f, 0xc4, 0x75, 0x53, 0x81, 0x06, 0xd0,
	0x93, 0x0c, 0x83, 0x10, 0x44, 0xfd, 0xd4, 0x93, 0x0c, 0xdd, 0xc1, 0x2e, 0xd5, 0x9c, 0x58, 0xa5,
	0xb1, 0x17, 0x82, 0xe8, 0xdf, 0x74, 0xfc, 0xf9, 0x7e, 0x36, 0x12, 0xd2, 0xce, 0x57, 0x59, 0x4c,
	0x55, 0x9e, 0x50, 0x65, 0x72, 0x65, 0x9a, 0x33, 0x32, 0x6c, 0x91, 0xd8, 0x4d, 0xc9, 0x4d, 0x3c,
	0xa1, 0x74, 0xc2, 0x98, 0xe6, 0xc6, 0xa4, 0x87, 0x06, 0x74, 0x02, 0xfd, 0x5c, 0xb1, 0xd5, 0x92,
	0xe3, 0x76, 0xfd, 0x83, 0x86, 0xa1, 0xff, 0xb0, 0xbd, 0xe0, 0x1b, 0xfc, 0xa7, 0x16, 0x2b, 0x88,
	0x86, 0xb0, 0xa7, 0x39, 0xe5, 0x72, 0xcd, 0x35, 0xee, 0xd4, 0xf2, 0x37, 0xaf, 0x5a, 0x08, 0xa5,
	0xbc, 0xb4, 0xd8, 0x77, 0x2d, 0x8e, 0xa1, 0x0b, 0x38, 0x60, 0x2b, 0x4d, 0xac, 0x54, 0xc5, 0x2d,
	0x97, 0x62, 0x6e, 0x71, 0x37, 0x04, 0x51, 0x27, 0xfd, 0xa5, 0x56, 0xf9, 0x4c, 0x59, 0xab, 0x72,
	0xdc, 0x73, 0x79, 0xc7, 0x2a, 0x7d, 0xee, 0x72, 0xfd, 0x10, 0x44, 0x7e, 0xda, 0xb0, 0xe9, 0xcd,
	0xeb, 0x2e, 0x00, 0xdb, 0x5d, 0x00, 0x3e, 0x76, 0x01, 0x78, 0xde, 0x07, 0xad, 0xed, 0x3e, 0x68,
	0xbd, 0xed, 0x83, 0xd6, 0xc3, 0xe5, 0x8f, 0x1d, 0x1e, 0x49, 0x21, 0x66, 0x5c, 0x96, 0xb2, 0x10,
	0x49, 0xf3, 0x3c, 0x4f, 0x07, 0x50, 0x2f, 0x92, 0xf9, 0xf5, 0xe2, 0x57, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x10, 0xbd, 0x80, 0xbe, 0x01, 0x00, 0x00,
}

func (m *MsgContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.Height))
		i--
		dAtA[i] = 0x49
	}
	if len(m.Bottom) > 0 {
		i -= len(m.Bottom)
		copy(dAtA[i:], m.Bottom)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Bottom)))
		i--
		dAtA[i] = 0x42
	}
	if m.DurationHeight != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.DurationHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Accept) > 0 {
		i -= len(m.Accept)
		copy(dAtA[i:], m.Accept)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Accept)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Module) > 0 {
		i -= len(m.Module)
		copy(dAtA[i:], m.Module)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Module)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContract(dAtA []byte, offset int, v uint64) int {
	offset -= sovContract(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Module)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Accept)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.DurationHeight != 0 {
		n += 1 + sovContract(uint64(m.DurationHeight))
	}
	l = len(m.Bottom)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.Height != 0 {
		n += 9
	}
	return n
}

func sovContract(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContract(x uint64) (n int) {
	return sovContract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Module", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Module = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accept", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accept = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationHeight", wireType)
			}
			m.DurationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DurationHeight |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bottom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bottom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContract
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContract
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContract
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContract        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContract          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContract = fmt.Errorf("proto: unexpected end of group")
)
